/*
 * Copyright (c) 2014, Swedish Institute of Computer Science.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 * 3. Neither the name of the Institute nor the names of its contributors
 *    may be used to endorse or promote products derived from this software
 *    without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE INSTITUTE AND CONTRIBUTORS ``AS IS'' AND
 * ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED.  IN NO EVENT SHALL THE INSTITUTE OR CONTRIBUTORS BE LIABLE
 * FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
 * OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
 * HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
 * OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
 * SUCH DAMAGE.
 */
/**
 * \file   A test program for ECC Diffie-Hellman in Contiki
 *
 * \author Oriol Piñol <oriol@sics.se>
 */

#include "contiki.h"
#include "ecc.h"
#include "secp256r1.c"

#include <stdio.h> 
/*---------------------------------------------------------------------------*/
PROCESS(ecc_test_process, "ECC test process");
AUTOSTART_PROCESSES(&ecc_test_process);

  static ecc_point_a public_alice,public_bob; 
  static u_word private_alice[NUMWORDS],private_bob[NUMWORDS];
  static ecc_param param;
  static u_word shared[NUMWORDS];
  static u_word signature[NUMWORDS];
  static u_word r_x[NUMWORDS];
      
/*---------------------------------------------------------------------------*/
PROCESS_THREAD(ecc_test_process, ev, data)
{
  PROCESS_BEGIN();

  clock_time_t time;

  get_curve_parameters(&param);

  printf("Alice Private Key Generation\n");
  ecc_generate_private_key(private_alice, &param);
  bigint_print(private_alice, NUMWORDS);

  printf("Bob Private Key Generation\n");
  ecc_generate_private_key(private_bob, &param);
  bigint_print(private_bob, NUMWORDS);

  printf("Alice Public Key Generation\n");
  time = clock_time();
  ecc_generate_public_key(private_alice, &public_alice, &param);
  time = clock_time() - time;
  bigint_print(&public_alice, NUMWORDS);
  printf("Time: %"PRIu32" ms.\n", (uint32_t)time);

  printf("Bob Public Key Generation\n");
  time = clock_time();
  ecc_generate_public_key(private_bob, &public_bob, &param);
  time = clock_time() - time;
  bigint_print(&public_bob, NUMWORDS);
  printf("Time: %"PRIu32" ms.\n", (uint32_t)time);

  printf("Alice Shared Key Generation (Alice private key + Bob public key)\n");
  time = clock_time();
  ecc_generate_shared_key(shared, private_alice, &public_bob, &param);
  time = clock_time() - time;

  printf("Shared secret generated by Alice:\n");
  bigint_print(shared, NUMWORDS);
  printf("Time: %"PRIu32" ms.\n", (uint32_t)time);

  printf("Bob Shared Key Generation (Bob private key + Alice public key)\n");
  time = clock_time();
  ecc_generate_shared_key(shared, private_bob, &public_alice, &param);
  time = clock_time() - time;

  printf("Shared secret generated by Bob:\n");
  bigint_print(shared, NUMWORDS);
  printf("Time: %"PRIu32" ms.\n", (uint32_t)time);


  printf("Alice signs message \"Hello Bob\"\n");
  time = clock_time();
  ecc_generate_signature(&private_alice, (const uint8_t *)"Hello Bob",
                       signature, r_x, &param);
  time = clock_time() - time;

  printf("Signature:\n");
  bigint_print(signature, NUMWORDS);
  printf("Time: %"PRIu32" ms.\n", (uint32_t)time);


  printf("Bob verifies signature received\n");
  time = clock_time();
  if(ecc_check_signature(&public_alice, (const uint8_t *) "Hello Bob",
                    signature, r_x, &param)) {
    printf("The signature is valid for the provided message\n");
  } else {
    printf("The signature is INVALID for the provided message\n");
  }
  time = clock_time() - time;
  printf("Time: %"PRIu32" ms.\n", (uint32_t)time);

  PROCESS_END();
}
/*---------------------------------------------------------------------------*/
